#//////////////////////////////////////////////////////////////////////////////
#
# Copyright (c) 2010-2022 Daniel Adler <dadler@uni-goettingen.de>,
#                         Tassilo Philipp <tphilipp@potion-studios.com>
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#
#//////////////////////////////////////////////////////////////////////////////


TOP		= ..
<$TOP/buildsys/mk/prolog.mk

# only C-stuff for now, b/c C++ on Plan9 is rather inexistant
DIRS = callf plain call_suite call_suite_aggrs suite thunk malloc_wx callback_plain callback_suite callback_suite_aggrs
#DIRS = plain_c++ callback_plain_c++ suite2 suite3 suite_floats ellipsis

<$TOP/buildsys/mk/epilog.mk
