
Signal-to-noise ratios for stellar CCD images,
based on:
  A)     8.0 inch aperture scope
  B)    18.0 mag per sq arcsec of sky
  C)       3 arcsec detection circle
  D)     100 sec longest single exp.
  E)     1.5 arcsec-per-pixel scale
  F)     100 elec/pixel readout noise
  G)      70 thermal elec/pixel/sec
  H) 2000000 star-signal constant
  Q)         Quit

Choose a letter or type '/' to continue/

 Mag.  1 sec  10s  100s 1000s 10000s
 10.0    20   143   577  1824  5769
 11.0     8    69   332  1050  3320
 12.0     3    30   176   556  1757
 13.0     1    13    84   265   839
 14.0     1     5    37   116   368
 15.0     0     2    15    48   153
 16.0     0     1     6    20    62
 17.0     0     0     2     8    25
 18.0     0     0     1     3    10
 19.0     0     0     0     1     4
 20.0     0     0     0     0     2

Press <Enter> to continue

Signal-to-noise ratios for stellar CCD images,
based on:
  A)     8.0 inch aperture scope
  B)    18.0 mag per sq arcsec of sky
  C)       3 arcsec detection circle
  D)     100 sec longest single exp.
  E)     1.5 arcsec-per-pixel scale
  F)     100 elec/pixel readout noise
  G)      70 thermal elec/pixel/sec
  H) 2000000 star-signal constant
  Q)         Quit

Choose a letter or type '/' to continueQ
