Will you enter the (A)ge of the universe or the (H)ubble parameterA
Enter age of the universe NOW in billions of years16
Enter (T)ime THEN or (R)edshift of the light we see NOWT
Enter age of the universe THEN in billions of years1

Age of the universe NOW  =  16.0000 billion years
Age of the universe THEN =   1.0000 billion years
Light travel time        =  15.0000 billion years
Scale of the universe NOW versus THEN =    6.350
Redshift of the light we see NOW      =    5.350
Distance of object THEN =  4.560 billion light-years
Distance of object NOW  = 28.951 billion light-years
Speed away from us THEN =  3.040 x speed of light
Speed away from us NOW  =  1.206 x speed of light
Hubble parameter THEN =     651.9 km/sec/megaparsec
Hubble parameter NOW  =      40.7 km/sec/megaparsec
