10 PRINT "PROGRAM FILE 1: NULL PRINT AND PRINTING QUOTED STRINGS."
20 PRINT "    ANSI STANDARD 3.2, 3.4, 5.2, 5.4, 12.2, 12.4"
30 PRINT
40 PRINT "*** NOTE: THIS PROGRAM MAKES USE OF THE END STATEMENT"
50 PRINT "    WHICH HAS NOT YET BEEN TESTED. IF SUBSEQUENT TESTS SHOW"
60 PRINT "    THIS FEATURE TO BE INCORRECTLY IMPLEMENTED, THEN THE "
70 PRINT "    VALIDITY OF THE RESULTS OF THIS TEST ROUTINE IS DOUBTFUL."
80 PRINT
90 PRINT
100 PRINT "                  * * * * * * * * * * * * * * * * * *"
110 PRINT "                  *                                 *"
120 PRINT "                  *   MINIMAL BASIC TEST PROGRAMS   *"
130 PRINT "                  *            VERSION 2            *"
135 PRINT "                  *                                 *"
140 PRINT "                  *            PRODUCT OF           *"
150 PRINT "                  *   NATIONAL BUREAU OF STANDARDS  *"
160 PRINT "                  *                                 *"
170 PRINT "                  * * * * * * * * * * * * * * * * * *"
180 PRINT
190 PRINT "SECTION 1.1: NULL PRINT. "
200 PRINT
210 PRINT "                               BEGIN TEST."
220 PRINT "            THIS IS LINE 1."
230 PRINT "            THIS IS LINE 2."
240 PRINT
250 PRINT "            THIS IS LINE 4, 3 SHOULD HAVE BEEN SKIPPED."
260 PRINT "            THIS IS LINE 5."
270 PRINT
280 PRINT
290 PRINT "          THIS IS LINE 8, 6 AND 7 SHOULD HAVE BEEN SKIPPED."
300 PRINT
310 PRINT "*** TEST PASSED IF LINES 2 AND 4 HAVE A BLANK LINE BETWEEN"
320 PRINT "    THEM, AND LINES 5 AND 8 TWO BLANK LINES ***"
330 PRINT
340 PRINT "                                END TEST."
350 PRINT
360 PRINT "SECTION 2.1: LEGAL CHARACTERS IN PRINTING QUOTED STRINGS."
390 PRINT
400 PRINT "                               BEGIN TEST."
410 PRINT
420 PRINT " LINE BELOW MUST PRINT OUT UPPER CASE LETTERS A THROUGH Z"
430 PRINT "                       ABCDEFGHIJKLMNOPQRSTUVWXYZ"
440 PRINT
450 PRINT " LINE BELOW MUST PRINT OUT DIGITS ZERO THROUGH NINE."
460 PRINT "                               0123456789"
470 PRINT
480 PRINT "LINE BELOW MUST PRINT OUT, IN THE FOLLOWING ORDER, LEFT"
490 PRINT "PARENTHESIS, RIGHT PARENTHESIS, AMPERSAND, EXCLAMATION"
500 PRINT "POINT, NUMBER SIGN, PERCENT, APOSTROPHE, QUESTION MARK,"
510 PRINT "ASTERISK, AND DOLLAR SIGN."
520 PRINT "                                   ()&!#%'?*$"
530 PRINT
540 PRINT "LINE BELOW MUST PRINT OUT, IN THE FOLLOWING ORDER, PLUS,"
550 PRINT "COMMA, MINUS, SLANT, LESS-THAN, EQUALS, GREATER-THAN,"
560 PRINT "CIRCUMFLEX, AND PERIOD."
570 PRINT "                                   +,-/<=>^."
580 PRINT
590 PRINT "LINE BELOW MUST PRINT OUT, IN THE FOLLOWING ORDER, COLON,"
600 PRINT "SPACE, SEMI-COLON, AND UNDERLINE."
610 PRINT "                                   : ;_"
620 PRINT
630 PRINT "*** TEST PASSED IF THE ABOVE SPECIFICATIONS WERE MET ***"
640 PRINT
650 PRINT "                                    END TEST."
660 PRINT
670 PRINT "SECTION 1.3: SPACES IN QUOTED STRINGS."
690 PRINT
700 PRINT "                                   BEGIN TEST."
710 PRINT
720 PRINT "                       ABCDEFGHIJKLMNOPQRSTUVWXYZ"
730 PRINT "                       A CD  GH   LM    RS     YZ"
740 PRINT
750 PRINT "*** TEST PASSED IF THE SECOND LINE OF ALPHA CHARACTERS IN "
760 PRINT "    THE ABOVE TEST HAS BLANKS WHERE THE LETTERS B, E, F,"
770 PRINT "    I, J, K, N, O, P, Q, T, U, V, W, AND X APPEAR IN THE "
775 PRINT "    FIRST LINE. ***"
780 PRINT
790 PRINT "                                END TEST."
800 PRINT
810 PRINT "SECTION 1.4: PRINTING THE NULL STRING."
830 PRINT
840 PRINT "                               BEGIN TEST."
850 PRINT
870 PRINT "THE NEXT STATEMENT PRINTS A NULL QUOTED STRING."
890 PRINT ""
900 PRINT "THE LINE ABOVE MUST BE BLANK AS A RESULT OF PRINTING"
910 PRINT "A NULL QUOTED STRING."
920 PRINT
930 PRINT "*** TEST PASSED IF THE ABOVE SPECIFICATIONS WERE MET ***"
940 PRINT
950 PRINT "                                END TEST."
960 PRINT
970 PRINT "END PROGRAM 1"
980 END
