10 PRINT "PROGRAM FILE 3: ERROR - MISPLACED END-STATEMENT."
20 PRINT "    ANSI STANDARD 4.2, 4.4"
30 PRINT
40 PRINT "SECTION 3.1: ERROR - MISPLACED END-STATEMENT."
50 PRINT
60 PRINT "THIS PROGRAM TESTS TO SEE IF THE BASIC PROCESSOR"
70 PRINT "ACCEPTS PROGRAMS CONTAINING AN END STATEMENT WHICH IS"
80 PRINT "NOT PHYSICALLY LAST."
90 PRINT
100 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
110 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
120 PRINT
130 PRINT "  1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
140 PRINT "     ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
150 PRINT "     BY THE PROCESSOR, OR"
160 PRINT
170 PRINT "  2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
180 PRINT
190 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
200 PRINT "FOR DETAILED CRITERIA."
210 PRINT
220 PRINT "                              BEGIN TEST."
230 PRINT
240 PRINT "IF THIS SENTENCE IS THE LAST SENTENCE PRINTED, THE PROCESSOR"
250 PRINT "DID NOT EXECUTE ANY MORE STATEMENTS AFTER ENCOUNTERING AN"
260 PRINT "END-STATEMENT IN THE MIDDLE OF THE PROGRAM."
270 END
280 PRINT
290 PRINT "IF THIS SENTENCE IS PRINTED OUT, THE PROCESSOR CONTINUED TO"
300 PRINT "EXECUTE STATEMENTS AFTER ENCOUNTERING AN END-STATEMENT"
310 PRINT "IN THE MIDDLE OF THE PROGRAM."
320 PRINT
330 PRINT "                              END TEST."
340 PRINT
350 PRINT "END PROGRAM 3"
360 END
