10 PRINT "PROGRAM FILE 4: ERROR - MISSING END-STATEMENT."
20 PRINT "    ANSI STANDARD 4.2, 4.4"
30 PRINT
40 PRINT "SECTION 4.1: ERROR - MISSING END-STATEMENT."
50 PRINT
60 PRINT "THIS PROGRAM TESTS TO SEE IF THE BASIC PROCESSOR"
70 PRINT "ACCEPTS PROGRAMS WHICH DO NOT CONTAIN AN END STATEMENT."
80 PRINT
90 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
100 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
110 PRINT
120 PRINT "  1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
130 PRINT "     ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
140 PRINT "     BY THE PROCESSOR, OR"
150 PRINT
160 PRINT "  2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
170 PRINT
180 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
190 PRINT "FOR DETAILED CRITERIA."
200 PRINT
210 PRINT "                              BEGIN TEST."
220 PRINT
230 PRINT "THE PROCESSOR IS EXECUTING A PROGRAM WHICH DOES NOT CONTAIN"
240 PRINT "AN END STATEMENT."
250 PRINT
260 PRINT "                              END TEST."
270 PRINT
280 PRINT "END PROGRAM 4"
