10 PRINT "PROGRAM FILE 23: INITIALIZATION OF STRING AND NUMERIC"
20 PRINT "        VARIABLES."
30 PRINT "    ANSI STANDARD 6.6"
40 PRINT
50 PRINT "SECTION 23.1: INITIALIZATION OF STRING OF NUMERIC"
60 PRINT "        VARIABLES."
70 PRINT
80 PRINT "THIS PROGRAM TESTS HOW THE IMPLEMENTATION TREATS"
90 PRINT "UNINITIALIZED VARIABLES. THE MINIMAL BASIC STANDARD"
100 PRINT "RECOMMENDS THAT THIS CONDITION BE TREATED AS AN "
110 PRINT "EXCEPTION. IN ANY CASE, THE DOCUMENTATION MUST"
120 PRINT "DESCRIBE THE ACTION OF THE PROCESSOR IN ORDER"
130 PRINT "FOR THE TEST TO PASS."
140 PRINT
150 PRINT "                         BEGIN TEST."
160 PRINT
170 PRINT "NEITHER A$ OR Y HAS BEEN ASSIGNED A VALUE."
180 PRINT
190 PRINT "THE IMPLEMENTATION-DEFINED INITIAL VALUE (SURROUNDED"
200 PRINT "    BY APOSTROPHES) FOR A$=";"'";A$;"'"
210 PRINT "THE IMPLEMENTATION-DEFINED INITIAL VALUE FOR Y =";Y
220 PRINT
230 PRINT "IF THE DOCUMENTATION FOR THIS IMPLEMENTATION CORRECTLY"
240 PRINT "   DESCRIBES THE RESULTS ABOVE, THEN"
250 PRINT "*** TEST PASSED ***"
260 PRINT
270 PRINT "                          END TEST."
280 PRINT
290 PRINT "END PROGRAM 23"
300 END
