10 PRINT "PROGRAM FILE 38: ERROR - USE OF ADJACENT OPERATORS."
20 PRINT "    ANSI STANDARD 7.2"
30 PRINT
40 PRINT "SECTION 38.1: ERROR - USE OF ADJACENT OPERATORS."
50 PRINT
60 PRINT "THIS SECTION TESTS WHETHER THE PROCESSOR DETECTS AND REPORTS"
70 PRINT "A NUMERIC EXPRESSION WHICH IS IMPROPERLY FORMED BECAUSE TWO"
80 PRINT "OPERATORS ARE USED IN SUCCESSION."
100 PRINT
110 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
120 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
130 PRINT
140 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
150 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
160 PRINT "      BY THE PROCESSOR, OR"
170 PRINT
180 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
190 PRINT
200 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
210 PRINT "FOR DETAILED CRITERIA."
220 PRINT
230 PRINT "               BEGIN TEST"
240 PRINT
250 LET A=4 ^ -2
260 PRINT "VALUE ASSIGNED FOR 4 ^ -2 = ";A
270 PRINT
280 PRINT "                END TEST"
290 PRINT
300 PRINT "END PROGRAM 38"
310 END
