10 PRINT "PROGRAM FILE 50: ERROR - FOR-STATEMENT WITHOUT A"
15 PRINT "        MATCHING NEXT-STATEMENT."
20 PRINT "    ANSI STANDARD 11.2, 11.4"
30 PRINT
40 PRINT "SECTION 50.1: ERROR - FOR-STATEMENT WITHOUT A"
50 PRINT "        MATCHING NEXT-STATEMENT."
60 PRINT
70 PRINT
80 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
90 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
100 PRINT
110 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
120 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
130 PRINT "      BY THE PROCESSOR, OR"
140 PRINT
150 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
160 PRINT
170 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
180 PRINT "FOR DETAILED CRITERIA."
190 PRINT
200 PRINT "                               BEGIN TEST."
210 PRINT
220 PRINT "ENTERING FOR-BLOCK; LOOP IS: FOR I=1 TO 5"
230 FOR I=1 TO 5
240 PRINT "CONTROL-VARIABLE = ";I
310 PRINT
320 PRINT "                                END TEST."
330 PRINT
340 PRINT "END PROGRAM 50"
350 END
