10 PRINT "PROGRAM FILE 51: ERROR - NEXT-STATEMENT WITHOUT A"
15 PRINT "        MATCHING FOR-STATEMENT."
20 PRINT "    ANSI STANDARD 11.2, 11.4"
30 PRINT
40 PRINT "SECTION 51.1: ERROR - NEXT-STATEMENT WITHOUT A"
50 PRINT "        MATCHING FOR-STATEMENT."
60 PRINT
70 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
80 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
90 PRINT
100 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
110 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
120 PRINT "      BY THE PROCESSOR, OR"
130 PRINT
140 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
150 PRINT
160 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAM USER'S MANUAL"
170 PRINT "FOR DETAILED CRITERIA."
180 PRINT
190 PRINT "                               BEGIN TEST."
200 PRINT
210 PRINT "ENTERING FOR-BLOCK; LOOP IS: FOR I=1 TO 5"
220 FOR I=1 TO 5
230 PRINT "CONTROL-VARIABLE = ";I
240 NEXT I
270 PRINT
280 PRINT "                                END TEST."
290 PRINT
300 PRINT "END PROGRAM 51"
303 STOP
306 NEXT I
310 END
