10 PRINT "PROGRAM FILE 53: ERROR - INTERLEAVED FOR-BLOCKS."
20 PRINT "    ANSI STANDARD 11.4"
30 PRINT
40 PRINT "SECTION 53.1: ERROR - INTERLEAVED FOR-BLOCKS."
50 PRINT
60 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
70 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
80 PRINT
90 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
100 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
110 PRINT "      BY THE PROCESSOR, OR"
120 PRINT
130 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
140 PRINT
150 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
160 PRINT "FOR DETAILED CRITERIA."
170 PRINT
180 PRINT "                               BEGIN TEST."
190 PRINT
200 PRINT "ENTERING FOR-BLOCKS; LOOPS ARE:"
205 PRINT "FOR I=1 TO 3 / FOR J=1 TO 5 / NEXT I / NEXT J"
210 FOR I=1 TO 3
220 FOR J=1 TO 5
230 PRINT "I = ";I;"       J = ";J
270 NEXT I
280 NEXT J
310 PRINT
320 PRINT "                                END TEST."
330 PRINT
340 PRINT "END PROGRAM 53"
350 END
