PROGRAM FILE 56: ARRAY ASSIGNMENT WITHOUT
        THE OPTION-STATEMENT.
    ANSI STANDARD 6.2, 6.4, 9.2, 9.4, 15.2, 15.4

SECTION 56.1: ONE-DIMENSIONAL ARRAYS WITHOUT THE
        DIM-STATEMENT.

                               BEGIN TEST.

*** TEST PASSED ***

                                END TEST.

SECTION 56.2: TWO-DIMENSIONAL ARRAYS WITHOUT THE
        DIM-STATEMENT.

                               BEGIN TEST.

***  TEST PASSED  ***

                               END TEST.

SECTION 56.3: ONE-DIMENSIONAL ARRAYS WITH THE
        DIM-STATEMENT.

                              BEGIN TEST.

*** TEST PASSED  ***

                                END TEST.


SECTION 56.4: TWO-DIMENSIONAL ARRAYS WITH THE
        DIM-STATEMENT.

                               BEGIN TEST.

***  TEST PASSED  ***

                                END TEST.


END PROGRAM 56
