10 PRINT "PROGRAM FILE 75: ERROR - DIM SETS ARRAY TO ONE DIMENSION"
13 PRINT "        AND REFERENCE IS MADE TO SIMPLE VARIABLE"
16 PRINT "        OF SAME NAME."
20 PRINT "    ANSI STANDARD 15.4, 6.4"
30 PRINT
40 PRINT "SECTION 75.1: ERROR - DIM SETS ARRAY TO ONE DIMENSION"
50 PRINT "        AND REFERENCE IS MADE TO SIMPLE VARIABLE"
60 PRINT "        OF SAME NAME."
70 PRINT
80 PRINT
90 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
100 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
110 PRINT
120 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
130 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
140 PRINT "      BY THE PROCESSOR, OR"
150 PRINT
160 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
170 PRINT
180 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
190 PRINT "FOR DETAILED CRITERIA."
200 PRINT
210 PRINT "               BEGIN TEST"
220 PRINT
230 DIM A(47)
240 LET A=777
300 PRINT "VARIABLE A WAS ASSIGNED 777. RESULTS BELOW:"
320 PRINT
400 PRINT "VARIABLE A = ";A
440 PRINT
450 PRINT "               END TEST"
460 PRINT
470 PRINT "END PROGRAM 75"
480 END
