10 PRINT "PROGRAM FILE 145: ERROR - TWO ARGUMENTS IN LIST FOR"
15 PRINT "        RND FUNCTION."
20 PRINT "    ANSI STANDARD 7.2, 7.4, 8.2, 8.4"
30 PRINT
40 PRINT "SECTION 145.1: ERROR - TWO ARGUMENTS IN LIST FOR"
45 PRINT "        RND FUNCTION."
50 PRINT
60 PRINT "THIS SECTION TESTS WHAT HAPPENS WHEN THE RND FUNCTION IS"
70 PRINT "INVOKED WITH TWO ARGUMENTS, INSTEAD OF NONE AS SPECIFIED"
80 PRINT "IN THE STANDARD."
90 PRINT
100 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
110 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
120 PRINT
130 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
140 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
150 PRINT "      BY THE PROCESSOR, OR"
160 PRINT
170 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
180 PRINT
190 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
200 PRINT "FOR DETAILED CRITERIA."
210 PRINT
220 PRINT "             BEGIN TEST"
230 PRINT
240 PRINT "ABOUT TO ATTEMPT INVOCATION OF RND."
250 LET A=RND(1,1)
260 PRINT "PROCESSOR HAS EVALUATED RND(1,1) = ";A
270 PRINT
280 PRINT "              END TEST"
290 PRINT
300 PRINT "END PROGRAM 145"
310 END
