10 PRINT "PROGRAM FILE 187: ERROR - SPACES AT THE BEGINNING OF A LINE."
15 PRINT "    ANSI STANDARD 3.4, 4.4"
20 PRINT
30 PRINT "SECTION 187.1: ERROR - SPACES AT THE BEGINNING OF A LINE."
40 PRINT
50 PRINT "     THIS PROGRAM TESTS TO SEE IF THE BASIC PROCESSOR"
60 PRINT "ACCEPTS PROGRAMS CONTAINING LINES BEGINNING WITH SPACES."
70 PRINT
80 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
90 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
100 PRINT
110 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
120 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
130 PRINT "      BY THE PROCESSOR, OR"
140 PRINT
150 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
160 PRINT
170 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
180 PRINT "FOR DETAILED CRITERIA."
190 PRINT
200 PRINT "                                BEGIN TEST."
210 PRINT
 220 PRINT "THE PROCESSOR HAS EXECUTED A LINE BEGINNING WITH A SPACE."
230 PRINT
240 PRINT "                                 END TEST."
250 PRINT
260 PRINT "END PROGRAM 187"
270 END
