10 PRINT "PROGRAM FILE 188: ERROR - SPACES WITHIN LINE-NUMBERS."
20 PRINT "    ANSI STANDARD 3.4, 4.4"
30 PRINT
40 PRINT "SECTION 188.1: ERROR - SPACES WITHIN LINE-NUMBERS."
50 PRINT
60 PRINT "THIS PROGRAM TESTS TO SEE IF THE BASIC PROCESSOR ACCEPTS"
70 PRINT "PROGRAMS CONTAINING SPACES WITHIN LINE-NUMBERS."
80 PRINT
90 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
100 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
110 PRINT
120 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
130 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
140 PRINT "      BY THE PROCESSOR, OR"
150 PRINT
160 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
170 PRINT
180 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
190 PRINT "FOR DETAILED CRITERIA."
200 PRINT
210 PRINT
220 PRINT "                              BEGIN TEST."
230 PRINT
2 40 PRINT "THE PROCESSOR HAS EXECUTED TWO LINES CONTAINING"
25 0 PRINT "SPACES WITHIN LINE-NUMBERS."
260 PRINT
270 PRINT "                               END TEST."
280 PRINT
290 PRINT "END PROGRAM 188"
300 END
