10 PRINT "PROGRAM FILE 193: ERROR - PRINT-ITEM QUOTED STRINGS"
15 PRINT "        CONTAINING DOUBLE QUOTES."
20 PRINT "    ANSI STANDARD 3.2, 12.2, 12.4"
30 PRINT
40 PRINT "SECTION 193.1: ERROR -PRINT-ITEM QUOTED STRINGS"
45 PRINT "        CONTAINING DOUBLE QUOTES."
50 PRINT
60 PRINT "THIS PROGRAM TESTS TO SEE IF THE BASIC PROCESSOR"
70 PRINT "ACCEPTS PROGRAMS CONTAINING TWO CONSECUTIVE OCCURRENCES"
80 PRINT "OF THE QUOTE CHARACTER WITHIN THE QUOTED STRING OF A"
90 PRINT "PRINT STATEMENT."
100 PRINT
110 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
120 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
130 PRINT
140 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
150 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
160 PRINT "      BY THE PROCESSOR, OR"
170 PRINT
180 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
190 PRINT
200 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
210 PRINT "FOR DETAILED CRITERIA."
220 PRINT
230 PRINT "                              BEGIN TEST."
240 PRINT
250 PRINT "A PRINT-ITEM CONTAINING AN ASTERISK, TWO CONSECUTIVE"
260 PRINT "OCCURRENCES OF THE QUOTE CHARACTER AND A QUESTION MARK "
270 PRINT "APPEARS IN THE NEXT STATEMENT AFTER THIS PARAGRAPH."
280 PRINT "CHECK THE NEXT LINE OF OUTPUT FOR THE PROCESSOR'S"
290 PRINT "INTERPRETATION."
300 PRINT "                       *""?"
310 PRINT
320 PRINT "                               END TEST."
330 PRINT
340 PRINT "END PROGRAM 193"
350 END
