10 PRINT "PROGRAM FILE 202: ERROR - LINES LONGER THAN 72 CHARACTERS."
20 PRINT "    ANSI STANDARD 4.4"
30 PRINT
40 PRINT "SECTION 202.1: ERROR - LINES LONGER THAN 72 CHARACTERS."
50 PRINT
60 PRINT "THIS PROGRAM TESTS TO SEE IF THE PROCESSOR ACCEPTS PROGRAMS"
70 PRINT "CONTAINING LINES LONGER THAN 72 CHARACTERS."
80 PRINT
90 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
100 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
110 PRINT
120 PRINT "  1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
130 PRINT "     ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
140 PRINT "     BY THE PROCESSOR, OR"
150 PRINT
160 PRINT "  2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
170 PRINT
180 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAM USER'S MANUAL"
190 PRINT "FOR DETAILED CRITERIA."
200 PRINT
210 PRINT "                              BEGIN TEST."
220 PRINT
230 PRINT "THE PROCESSOR HAS EXECUTED A STATEMENT CONTAINING"; 9999     -9921;
235 PRINT "CHARACTERS."
240 PRINT
250 PRINT "                                END TEST."
260 PRINT
270 PRINT "END PROGRAM 202"
280 END
