10 PRINT "PROGRAM FILE 205: ERROR - ASSIGNED STRING CONTAINING"
15 PRINT "        LOWERCASE CHARACTERS."
20 PRINT "    ANSI STANDARD 3.2, 3.4, 9.2"
30 PRINT
40 PRINT "SECTION 205.1: ERROR - ASSIGNED STRING CONTAINING"
45 PRINT "        LOWERCASE CHARACTERS."
50 PRINT
60 PRINT "THIS PROGRAM TESTS TO SEE IF THE PROCESSOR ACCEPTS PROGRAMS"
70 PRINT "CONTAINING LOWERCASE CHARACTERS IN THE QUOTED STRING OF A"
80 PRINT "LET-STATEMENT."
90 PRINT
100 PRINT "THIS IS A TEST FOR A NON-STANDARD FEATURE OF MINIMAL BASIC."
110 PRINT "TO PASS THIS TEST, THE PROCESSOR MUST EITHER:"
120 PRINT
130 PRINT "   1) ACCEPT THE PROGRAM AND BE ACCOMPANIED BY DOCUMENTATION"
140 PRINT "      ACCURATELY DESCRIBING THE FEATURE'S INTERPRETATION"
150 PRINT "      BY THE PROCESSOR, OR"
160 PRINT
170 PRINT "   2) REJECT THE PROGRAM WITH AN APPROPRIATE ERROR MESSAGE"
180 PRINT
190 PRINT "SEE THE NBS MINIMAL BASIC TEST PROGRAMS USER'S MANUAL"
200 PRINT "FOR DETAILED CRITERIA."
210 PRINT
220 PRINT "                              BEGIN TEST."
230 PRINT
240 LET A$="abcdefghijklmnopqr"
250 PRINT "AN ASSIGNMENT STATEMENT HAS ATTEMPTED TO ASSOCIATE A STRING"
260 PRINT "CONSISTING OF THE FIRST 18 CHARACTERS OF THE ALPHABET, (A-R)"
270 PRINT "IN LOWERCASE, WITH A$."
290 PRINT "A$=";A$
300 PRINT
310 PRINT "                                END TEST."
320 PRINT
330 PRINT "END PROGRAM 205"
340 END
