  10 FOR I = 1 TO 45
  20   PRINT " ";2^I;" ";
  30 NEXT I
  40 END
9900 REM ------------------------------------------------------------------------
9910 REM Purpose: SAMPLE example 
9920 REM  Author: General Electric
9930 REM    Date: 1966-08-29
9940 REM    Note: OPTION VERSION MARK-I
9950 REM  Origin: 202026A_BASIC_Language_Reference_Manual_Jan1967.pdf
9960 REM    Page: 25
9970 REM ------------------------------------------------------------------------
