  10 FOR N = 1 TO 7
  20   PRINT N, SQR (N)
  30 NEXT N
  40 PRINT "DONE"
  50 END
9900 REM ------------------------------------------------------------------------
9910 REM Purpose: SAMPLE example 
9920 REM  Author: General Electric
9930 REM    Date: 1965-12-17
9940 REM    Note: OPTION VERSION MARK-I
9950 REM  Origin: 202026A_BASIC_Language_Reference_Manual_Jan1967.pdf
9960 REM    Page: 14
9970 REM ------------------------------------------------------------------------
