10 REM Purpose:
20 REM
100 rem test
110 ' test
120 rem ' test
130 ' rem test
140 print:rem test
150 print:rem ' test
160 ' label1:'test
170 ' label2:'rem test
180 ' label3 : ' test
190 ' label4 : ' rem test
200 rem test : test
210 rem test : ' test
220 ' test : test
230 ' test : rem test
240 ' test : ' test
250 print "hello":print"there":print"world":rem hello there worldd
260 print"a":print"b":print"c" 'abc
270 print:print:rem test
280 print:print ' rem test
290 print:print:rem ' test
300 rem:test
310 rem:'test
320 rem: ' test
330 rem:rem test
340 ':test
350 ':rem test
360 rem : test
370 rem : ' test
380 rem : rem test
390 'test:test
