ESTR(ERR_OK, "OK")
ESTR(ERR_DIVBY0, "Division by zero")
ESTR(ERR_FP, "Floating point exception")
ESTR(ERR_VOF, "Overflow")
ESTR(ERR_SOR, "Subscript out of range")
ESTR(ERR_IBUFOF, "Icode buffer full")
ESTR(ERR_GSTKOF, "GOSUB too many nested")
ESTR(ERR_GSTKUF, "RETURN stack underflow")
ESTR(ERR_ASTKOF, "Argument stack overflow")
ESTR(ERR_UNDEFARG, "Undefined argument")
ESTR(ERR_LSTKOF, "FOR too many nested")
ESTR(ERR_LSTKUF, "NEXT without FOR")
ESTR(ERR_FORWOV, "FOR without variable")
ESTR(ERR_FORWOTO, "FOR without TO")
ESTR(ERR_LETWOV, "LET without variable")
ESTR(ERR_IFWOC, "IF without condition")
ESTR(ERR_IFSTKOF, "IF stack overflow")
ESTR(ERR_IFSTKUF, "IF stack underflow")
ESTR(ERR_ULN, "Undefined line number")
ESTR(ERR_PAREN, "\'(\' or \')\' expected")
ESTR(ERR_VWOEQ, "\'=\' expected")
ESTR(ERR_COM, "Cannot use system command") // v0.83 メッセージ文変更
ESTR(ERR_VALUE, "Illegal value")      // 追加
ESTR(ERR_RANGE, "Out of range value") // 追加
ESTR(ERR_NOPRG, "Program not found")  // 追加
ESTR(ERR_SYNTAX, "Syntax error")
ESTR(ERR_SYS, "Internal error")
ESTR(ERR_CTR_C, "Break")
ESTR(ERR_LONG, "Line too long")
ESTR(ERR_FILE_WRITE, "File write error") //  追加
ESTR(ERR_FILE_READ, "File read error") //  追加
ESTR(ERR_GPIO, "Cannot use GPIO function") //  追加
ESTR(ERR_LONGPATH, "Too long path") //  追加
ESTR(ERR_FILE_OPEN, "File open error") //  追加
ESTR(ERR_FILE_NOT_OPEN, "File not open")
ESTR(ERR_SD_NOT_READY, "SD I/O error") //  追加
ESTR(ERR_BAD_FNAME, "Bad file name") //  追加
ESTR(ERR_NOT_SUPPORTED, "Not supported") //  追加
ESTR(ERR_SCREEN_FULL, "Out of video memory")
ESTR(ERR_OOM, "Out of memory")
ESTR(ERR_CONT, "Can't continue")
ESTR(ERR_UNDEFARR, "Undefined array")
ESTR(ERR_UNDEFPROC, "Undefined procedure")
ESTR(ERR_UNDEFLABEL, "Undefined label")
ESTR(ERR_DUPPROC, "Duplicate procedure")
ESTR(ERR_DUPLABEL, "Duplicate label")
ESTR(ERR_OOD, "Out of data")
ESTR(ERR_IO, "I/O error")
ESTR(ERR_TYPE, "Type mismatch")
ESTR(ERR_GLOBAL, "Local variable outside procedure")
ESTR(ERR_EMPTY, "Empty list")
ESTR(ERR_NOENDIF, "ENDIF not found")
ESTR(ERR_ARGS, "Not enough arguments")
ESTR(ERR_FORMAT, "File format error")
ESTR(ERR_USING, "USING format error")
ESTR(ERR_NETWORK, "Network error")
ESTR(ERR_NOT_DIR, "Not a directory")
ESTR(ERR_WHILEWOW, "WHILE without WEND")
ESTR(ERR_STACKOF, "System stack overflow")
ESTR(ERR_FILE_SEEK, "File seek error")
ESTR(ERR_TSF, "Failed to init synth")
ESTR(ERR_UNK, "Unknown command")
ESTR(ERR_PROCWOC, "PROC without CALL/FN")
ESTR(ERR_CHAIN, "CHAIN failed")
ESTR(ERR_LONG_PATH, "Path too long")
