APP       = resolve_self${APP_SUFFIX}
OBJS      = main.o
SRCTOP    = ${VPATH}/../..
BLDTOP    = ../..
CFLAGS   += -I${SRCTOP}/dynload
LDLIBS_D  = -L${BLDTOP}/dynload -ldynload_s 
.PHONY: all clean install
all: ${APP}
${APP}: ${OBJS} 
	# some linkers (e.g. apple's mach-o linker) don't know --export-dynamic, so
	# try without if link fails; this is a bit hacky and should prob be part of
	# of the ./configure run
	${CC} ${CFLAGS} ${LDFLAGS} -Wl,--export-dynamic ${OBJS} ${LDLIBS_D} ${LDLIBS} -o ${APP} || \
		${CC} ${CFLAGS} ${LDFLAGS} ${OBJS} ${LDLIBS_D} ${LDLIBS} -o ${APP}
clean:
	rm -f ${APP} ${OBJS}
install:
	mkdir -p ${PREFIX}/test
	cp ${APP} ${PREFIX}/test

