00100 REM ----------------------------------------------------
00110 REM FILENAME:  delete1.bas
00120 REM  PURPOSE:  Verify DELETE <first> - <last>
00130 REM   AUTHOR:  Howard Wulf AF5NE
00140 REM     DATE:  October 10th, 2014
00150 REM ----------------------------------------------------
01000 delete 3000-3999
02000 REM ----------------------------------------------------
03030 ERROR 1
03040 ERROR 1
03050 ERROR 1
03060 ERROR 1
03070 ERROR 1
03080 ERROR 1
03090 ERROR 1
19900 REM ----------------------------------------------------
19910 REM *** ALL TESTS PASSED ***
19920 REM ----------------------------------------------------
19930 PRINT "*** ALL TESTS PASSED ***"
19999 END

