                X   X   X   X   X   X   X   X   X   
       NOT NOT AND  OR XOR  <   <=  =   >=  >   <>  
X   Y   X   Y   Y   Y   Y   Y   Y   Y   Y   Y   Y   
=   =   =   =   =   =   =   =   =   =   =   =   =   
T   T   F   F   T   T   F   F   T   T   T   F   F   
T   F   F   T   F   T   T   T   T   F   F   F   T   
F   T   T   F   F   T   T   F   F   F   T   T   T   
F   F   T   T   F   F   F   F   T   T   T   F   F   
