TESTCASE #1	E=1	R=0	A$=[]
	F=1	N=0
*** TEST PASSED ***
TESTCASE #2	E=0	R=32	A$=[ ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #3	E=0	R=51	A$=[3]
	F=0	N=51
*** TEST PASSED ***
TESTCASE #4	E=0	R=122	A$=[z]
	F=0	N=122
*** TEST PASSED ***
TESTCASE #5	E=0	R=32	A$=[  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #6	E=0	R=32	A$=[ 3]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #7	E=0	R=32	A$=[ z]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #8	E=0	R=51	A$=[3 ]
	F=0	N=51
*** TEST PASSED ***
TESTCASE #9	E=0	R=122	A$=[z ]
	F=0	N=122
*** TEST PASSED ***
TESTCASE #10	E=0	R=32	A$=[ 3 ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #11	E=0	R=32	A$=[ z ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #12	E=0	R=32	A$=[ LLLL]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #13	E=0	R=32	A$=[    ''    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #14	E=0	R=32	A$=[   oo     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #15	E=0	R=32	A$=[ 00  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #16	E=0	R=32	A$=[   \\\\  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #17	E=0	R=32	A$=[ lllll  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #18	E=0	R=32	A$=[    uuuu  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #19	E=0	R=32	A$=[  a  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #20	E=0	R=32	A$=[       ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #21	E=0	R=32	A$=[ hh     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #22	E=0	R=32	A$=[  h   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #23	E=0	R=32	A$=[ )]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #24	E=0	R=32	A$=[    5   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #25	E=0	R=32	A$=[  2 ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #26	E=0	R=32	A$=[ -   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #27	E=0	R=100	A$=[dd ]
	F=0	N=100
*** TEST PASSED ***
TESTCASE #28	E=0	R=32	A$=[  tttt   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #29	E=0	R=32	A$=[  ::::   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #30	E=0	R=32	A$=[   ___   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #31	E=0	R=32	A$=[     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #32	E=0	R=32	A$=[       ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #33	E=0	R=32	A$=[ _____  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #34	E=0	R=32	A$=[ S ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #35	E=0	R=32	A$=[  FFFF ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #36	E=0	R=32	A$=[    kkk]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #37	E=0	R=32	A$=[    NNNN  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #38	E=0	R=32	A$=[   mmmm  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #39	E=0	R=32	A$=[    ,,,,, ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #40	E=0	R=79	A$=[OO   ]
	F=0	N=79
*** TEST PASSED ***
TESTCASE #41	E=0	R=32	A$=[   HHHH  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #42	E=0	R=32	A$=[ < ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #43	E=0	R=32	A$=[   j    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #44	E=0	R=32	A$=[    yyyy    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #45	E=0	R=32	A$=[  +++ ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #46	E=0	R=111	A$=[o  ]
	F=0	N=111
*** TEST PASSED ***
TESTCASE #47	E=0	R=32	A$=[    ((]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #48	E=0	R=32	A$=[     uu     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #49	E=0	R=32	A$=[    00     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #50	E=0	R=32	A$=[     HH  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #51	E=0	R=32	A$=[     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #52	E=0	R=32	A$=[  G   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #53	E=0	R=32	A$=[    {{{{ ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #54	E=0	R=32	A$=[    ]]]     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #55	E=0	R=67	A$=[CCC]
	F=0	N=67
*** TEST PASSED ***
TESTCASE #56	E=0	R=32	A$=[     44  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #57	E=0	R=94	A$=[^^  ]
	F=0	N=94
*** TEST PASSED ***
TESTCASE #58	E=0	R=32	A$=[    QQ    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #59	E=0	R=32	A$=[     FFFF  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #60	E=0	R=32	A$=[ n   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #61	E=0	R=32	A$=[    hh  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #62	E=0	R=53	A$=[555    ]
	F=0	N=53
*** TEST PASSED ***
TESTCASE #63	E=0	R=32	A$=[    YYYY ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #64	E=0	R=32	A$=[    w     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #65	E=0	R=77	A$=[MMMM ]
	F=0	N=77
*** TEST PASSED ***
TESTCASE #66	E=0	R=32	A$=[ JJJJ    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #67	E=0	R=32	A$=[    %%    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #68	E=0	R=32	A$=[     *  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #69	E=0	R=32	A$=[    @@@   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #70	E=0	R=73	A$=[I ]
	F=0	N=73
*** TEST PASSED ***
TESTCASE #71	E=0	R=32	A$=[    ss  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #72	E=0	R=32	A$=[  f ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #73	E=0	R=32	A$=[   D  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #74	E=0	R=35	A$=[###    ]
	F=0	N=35
*** TEST PASSED ***
TESTCASE #75	E=0	R=32	A$=[    '     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #76	E=0	R=32	A$=[  dd    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #77	E=0	R=32	A$=[ TT    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #78	E=0	R=32	A$=[  vvv ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #79	E=0	R=32	A$=[    X ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #80	E=0	R=32	A$=[    %   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #81	E=0	R=32	A$=[  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #82	E=0	R=32	A$=[ 5555   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #83	E=0	R=70	A$=[FFFF   ]
	F=0	N=70
*** TEST PASSED ***
TESTCASE #84	E=0	R=32	A$=[     %%  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #85	E=0	R=32	A$=[     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #86	E=0	R=32	A$=[  ~~~~    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #87	E=0	R=32	A$=[   ||    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #88	E=0	R=32	A$=[     SSS     ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #89	E=0	R=32	A$=[   6666 ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #90	E=0	R=32	A$=[    ww   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #91	E=0	R=32	A$=[  1111   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #92	E=0	R=32	A$=[ K ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #93	E=0	R=32	A$=[  ttttt ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #94	E=0	R=32	A$=[ OOOOO   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #95	E=0	R=32	A$=[ E  ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #96	E=0	R=32	A$=[ PPPPP   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #97	E=0	R=32	A$=[    == ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #98	E=0	R=32	A$=[ VVVV    ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #99	E=0	R=32	A$=[ c   ]
	F=0	N=32
*** TEST PASSED ***
TESTCASE #100	E=0	R=32	A$=[    yyyy     ]
	F=0	N=32
*** TEST PASSED ***
*** ALL TESTS PASSED ***
