TESTCASE #1	E=0	R=0	A$=[]	B$=[]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #2	E=0	R=0	A$=[ ]	B$=[ ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #3	E=0	R=0	A$=[3]	B$=[3]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #4	E=0	R=0	A$=[z]	B$=[z]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #5	E=0	R=0	A$=[  ]	B$=[  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #6	E=0	R=0	A$=[ 3]	B$=[ 3]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #7	E=0	R=0	A$=[ z]	B$=[ z]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #8	E=0	R=0	A$=[3 ]	B$=[3 ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #9	E=0	R=0	A$=[z ]	B$=[z ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #10	E=0	R=0	A$=[ 3 ]	B$=[ 3 ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #11	E=0	R=0	A$=[ z ]	B$=[ z ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #12	E=0	R=0	A$=[ LLLL]	B$=[ LLLL]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #13	E=0	R=0	A$=[    ''    ]	B$=[    ''    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #14	E=0	R=0	A$=[   oo     ]	B$=[   oo     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #15	E=0	R=0	A$=[ 00  ]	B$=[ 00  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #16	E=0	R=0	A$=[   \\\\  ]	B$=[   \\\\  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #17	E=0	R=0	A$=[ lllll  ]	B$=[ lllll  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #18	E=0	R=0	A$=[    uuuu  ]	B$=[    uuuu  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #19	E=0	R=0	A$=[  a  ]	B$=[  a  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #20	E=0	R=0	A$=[       ]	B$=[       ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #21	E=0	R=0	A$=[ hh     ]	B$=[ hh     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #22	E=0	R=0	A$=[  h   ]	B$=[  h   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #23	E=0	R=0	A$=[ )]	B$=[ )]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #24	E=0	R=0	A$=[    5   ]	B$=[    5   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #25	E=0	R=0	A$=[  2 ]	B$=[  2 ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #26	E=0	R=0	A$=[ -   ]	B$=[ -   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #27	E=0	R=0	A$=[dd ]	B$=[dd ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #28	E=0	R=0	A$=[  tttt   ]	B$=[  tttt   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #29	E=0	R=0	A$=[  ::::   ]	B$=[  ::::   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #30	E=0	R=0	A$=[   ___   ]	B$=[   ___   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #31	E=0	R=0	A$=[     ]	B$=[     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #32	E=0	R=0	A$=[       ]	B$=[       ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #33	E=0	R=0	A$=[ _____  ]	B$=[ _____  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #34	E=0	R=0	A$=[ S ]	B$=[ S ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #35	E=0	R=0	A$=[  FFFF ]	B$=[  FFFF ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #36	E=0	R=0	A$=[    kkk]	B$=[    kkk]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #37	E=0	R=0	A$=[    NNNN  ]	B$=[    NNNN  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #38	E=0	R=0	A$=[   mmmm  ]	B$=[   mmmm  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #39	E=0	R=0	A$=[    ,,,,, ]	B$=[    ,,,,, ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #40	E=0	R=0	A$=[OO   ]	B$=[OO   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #41	E=0	R=0	A$=[   HHHH  ]	B$=[   HHHH  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #42	E=0	R=0	A$=[ < ]	B$=[ < ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #43	E=0	R=0	A$=[   j    ]	B$=[   j    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #44	E=0	R=0	A$=[    yyyy    ]	B$=[    yyyy    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #45	E=0	R=0	A$=[  +++ ]	B$=[  +++ ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #46	E=0	R=0	A$=[o  ]	B$=[o  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #47	E=0	R=0	A$=[    ((]	B$=[    ((]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #48	E=0	R=0	A$=[     uu     ]	B$=[     uu     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #49	E=0	R=0	A$=[    00     ]	B$=[    00     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #50	E=0	R=0	A$=[     HH  ]	B$=[     HH  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #51	E=0	R=0	A$=[     ]	B$=[     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #52	E=0	R=0	A$=[  G   ]	B$=[  G   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #53	E=0	R=0	A$=[    {{{{ ]	B$=[    {{{{ ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #54	E=0	R=0	A$=[    ]]]     ]	B$=[    ]]]     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #55	E=0	R=0	A$=[CCC]	B$=[CCC]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #56	E=0	R=0	A$=[     44  ]	B$=[     44  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #57	E=0	R=0	A$=[^^  ]	B$=[^^  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #58	E=0	R=0	A$=[    QQ    ]	B$=[    QQ    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #59	E=0	R=0	A$=[     FFFF  ]	B$=[     FFFF  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #60	E=0	R=0	A$=[ n   ]	B$=[ n   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #61	E=0	R=0	A$=[    hh  ]	B$=[    hh  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #62	E=0	R=0	A$=[555    ]	B$=[555    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #63	E=0	R=0	A$=[    YYYY ]	B$=[    YYYY ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #64	E=0	R=0	A$=[    w     ]	B$=[    w     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #65	E=0	R=0	A$=[MMMM ]	B$=[MMMM ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #66	E=0	R=0	A$=[ JJJJ    ]	B$=[ JJJJ    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #67	E=0	R=0	A$=[    %%    ]	B$=[    %%    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #68	E=0	R=0	A$=[     *  ]	B$=[     *  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #69	E=0	R=0	A$=[    @@@   ]	B$=[    @@@   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #70	E=0	R=0	A$=[I ]	B$=[I ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #71	E=0	R=0	A$=[    ss  ]	B$=[    ss  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #72	E=0	R=0	A$=[  f ]	B$=[  f ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #73	E=0	R=0	A$=[   D  ]	B$=[   D  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #74	E=0	R=0	A$=[###    ]	B$=[###    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #75	E=0	R=0	A$=[    '     ]	B$=[    '     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #76	E=0	R=0	A$=[  dd    ]	B$=[  dd    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #77	E=0	R=0	A$=[ TT    ]	B$=[ TT    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #78	E=0	R=0	A$=[  vvv ]	B$=[  vvv ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #79	E=0	R=0	A$=[    X ]	B$=[    X ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #80	E=0	R=0	A$=[    %   ]	B$=[    %   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #81	E=0	R=0	A$=[  ]	B$=[  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #82	E=0	R=0	A$=[ 5555   ]	B$=[ 5555   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #83	E=0	R=0	A$=[FFFF   ]	B$=[FFFF   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #84	E=0	R=0	A$=[     %%  ]	B$=[     %%  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #85	E=0	R=0	A$=[     ]	B$=[     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #86	E=0	R=0	A$=[  ~~~~    ]	B$=[  ~~~~    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #87	E=0	R=0	A$=[   ||    ]	B$=[   ||    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #88	E=0	R=0	A$=[     SSS     ]	B$=[     SSS     ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #89	E=0	R=0	A$=[   6666 ]	B$=[   6666 ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #90	E=0	R=0	A$=[    ww   ]	B$=[    ww   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #91	E=0	R=0	A$=[  1111   ]	B$=[  1111   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #92	E=0	R=0	A$=[ K ]	B$=[ K ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #93	E=0	R=0	A$=[  ttttt ]	B$=[  ttttt ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #94	E=0	R=0	A$=[ OOOOO   ]	B$=[ OOOOO   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #95	E=0	R=0	A$=[ E  ]	B$=[ E  ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #96	E=0	R=0	A$=[ PPPPP   ]	B$=[ PPPPP   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #97	E=0	R=0	A$=[    == ]	B$=[    == ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #98	E=0	R=0	A$=[ VVVV    ]	B$=[ VVVV    ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #99	E=0	R=0	A$=[ c   ]	B$=[ c   ]
	F=0	N=0
*** TEST PASSED ***
TESTCASE #100	E=0	R=0	A$=[    yyyy     ]	B$=[    yyyy     ]
	F=0	N=0
*** TEST PASSED ***
*** ALL TESTS PASSED ***
