TESTCASE #1	E=0	R$=[]	A$=[]	X=0
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #2	E=0	R$=[ ]	A$=[ ]	X=1
	F=0	S$=[ ]
*** TEST PASSED ***
TESTCASE #3	E=1	R$=[]	A$=[3]	X=-1
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #4	E=0	R$=[]	A$=[z]	X=0.4
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #5	E=0	R$=[]	A$=[  ]	X=-0.4
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #6	E=0	R$=[]	A$=[ 3]	X=0.6
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #7	E=0	R$=[]	A$=[ z]	X=-0.6
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #8	E=0	R$=[3 ]	A$=[3 ]	X=254
	F=0	S$=[3 ]
*** TEST PASSED ***
TESTCASE #9	E=0	R$=[z ]	A$=[z ]	X=255
	F=0	S$=[z ]
*** TEST PASSED ***
TESTCASE #10	E=0	R$=[ 3 ]	A$=[ 3 ]	X=256
	F=0	S$=[ 3 ]
*** TEST PASSED ***
TESTCASE #11	E=0	R$=[ z ]	A$=[ z ]	X=32000
	F=0	S$=[ z ]
*** TEST PASSED ***
TESTCASE #12	E=0	R$=[]	A$=[ LLLL]	X=-0.227229
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #13	E=0	R$=[]	A$=[    ''    ]	X=-0.239157
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #14	E=0	R$=[]	A$=[   oo     ]	X=-0.213586
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #15	E=0	R$=[]	A$=[ 00  ]	X=0.274675
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #16	E=0	R$=[]	A$=[   \\\\  ]	X=0.169766
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #17	E=0	R$=[]	A$=[ lllll  ]	X=0.318766
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #18	E=0	R$=[]	A$=[    uuuu  ]	X=0.0206658
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #19	E=0	R$=[]	A$=[  a  ]	X=0.188257
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #20	E=0	R$=[]	A$=[       ]	X=-0.277537
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #21	E=0	R$=[]	A$=[ hh     ]	X=-0.481303
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #22	E=0	R$=[]	A$=[  h   ]	X=0.43556
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #23	E=0	R$=[]	A$=[ )]	X=-0.210971
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #24	E=0	R$=[]	A$=[    5   ]	X=-0.455216
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #25	E=1	R$=[]	A$=[  2 ]	X=-110.907
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #26	E=0	R$=[ -   ]	A$=[ -   ]	X=105.632
	F=0	S$=[ -   ]
*** TEST PASSED ***
TESTCASE #27	E=1	R$=[]	A$=[dd ]	X=-114.341
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #28	E=0	R$=[  tttt   ]	A$=[  tttt   ]	X=109.706
	F=0	S$=[  tttt   ]
*** TEST PASSED ***
TESTCASE #29	E=0	R$=[  ::::   ]	A$=[  ::::   ]	X=109.198
	F=0	S$=[  ::::   ]
*** TEST PASSED ***
TESTCASE #30	E=0	R$=[   ___   ]	A$=[   ___   ]	X=85.8773
	F=0	S$=[   ___   ]
*** TEST PASSED ***
TESTCASE #31	E=1	R$=[]	A$=[     ]	X=-58.3548
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #32	E=0	R$=[       ]	A$=[       ]	X=29.6397
	F=0	S$=[       ]
*** TEST PASSED ***
TESTCASE #33	E=1	R$=[]	A$=[ _____  ]	X=-108.36
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #34	E=1	R$=[]	A$=[ S ]	X=-46.5199
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #35	E=0	R$=[  FFFF ]	A$=[  FFFF ]	X=112.521
	F=0	S$=[  FFFF ]
*** TEST PASSED ***
TESTCASE #36	E=0	R$=[    kkk]	A$=[    kkk]	X=45.4151
	F=0	S$=[    kkk]
*** TEST PASSED ***
TESTCASE #37	E=0	R$=[    NNNN  ]	A$=[    NNNN  ]	X=101.129
	F=0	S$=[    NNNN  ]
*** TEST PASSED ***
TESTCASE #38	E=0	R$=[   mmmm  ]	A$=[   mmmm  ]	X=65.0473
	F=0	S$=[   mmmm  ]
*** TEST PASSED ***
TESTCASE #39	E=0	R$=[    ,,,,, ]	A$=[    ,,,,, ]	X=48.4012
	F=0	S$=[    ,,,,, ]
*** TEST PASSED ***
TESTCASE #40	E=0	R$=[OO   ]	A$=[OO   ]	X=122.294
	F=0	S$=[OO   ]
*** TEST PASSED ***
TESTCASE #41	E=1	R$=[]	A$=[   HHHH  ]	X=-56.1094
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #42	E=1	R$=[]	A$=[ < ]	X=-121.087
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #43	E=1	R$=[]	A$=[   j    ]	X=-123.517
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #44	E=1	R$=[]	A$=[    yyyy    ]	X=-97.6301
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #45	E=1	R$=[]	A$=[  +++ ]	X=-64.0001
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #46	E=1	R$=[]	A$=[o  ]	X=-25.6888
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #47	E=0	R$=[    ((]	A$=[    ((]	X=14.8006
	F=0	S$=[    ((]
*** TEST PASSED ***
TESTCASE #48	E=1	R$=[]	A$=[     uu     ]	X=-61.0877
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #49	E=1	R$=[]	A$=[    00     ]	X=-66.6381
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #50	E=1	R$=[]	A$=[     HH  ]	X=-5476.5
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #51	E=1	R$=[]	A$=[     ]	X=-21210.3
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #52	E=1	R$=[]	A$=[  G   ]	X=-28757.2
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #53	E=1	R$=[]	A$=[    {{{{ ]	X=-28732.2
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #54	E=0	R$=[    ]]]     ]	A$=[    ]]]     ]	X=12730.3
	F=0	S$=[    ]]]     ]
*** TEST PASSED ***
TESTCASE #55	E=1	R$=[]	A$=[CCC]	X=-1830.69
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #56	E=0	R$=[     44  ]	A$=[     44  ]	X=5486.39
	F=0	S$=[     44  ]
*** TEST PASSED ***
TESTCASE #57	E=0	R$=[^^  ]	A$=[^^  ]	X=22405.9
	F=0	S$=[^^  ]
*** TEST PASSED ***
TESTCASE #58	E=0	R$=[    QQ    ]	A$=[    QQ    ]	X=30809.8
	F=0	S$=[    QQ    ]
*** TEST PASSED ***
TESTCASE #59	E=1	R$=[]	A$=[     FFFF  ]	X=-28930.6
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #60	E=1	R$=[]	A$=[ n   ]	X=-6014.53
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #61	E=0	R$=[    hh  ]	A$=[    hh  ]	X=17414.6
	F=0	S$=[    hh  ]
*** TEST PASSED ***
TESTCASE #62	E=1	R$=[]	A$=[555    ]	X=-10538.3
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #63	E=1	R$=[]	A$=[    YYYY ]	X=-17536.3
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #64	E=1	R$=[]	A$=[    w     ]	X=-8856.62
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #65	E=1	R$=[]	A$=[MMMM ]	X=-5140.12
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #66	E=1	R$=[]	A$=[ JJJJ    ]	X=-8595.31
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #67	E=1	R$=[]	A$=[    %%    ]	X=-3382.87
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #68	E=1	R$=[]	A$=[     *  ]	X=-5002.07
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #69	E=1	R$=[]	A$=[    @@@   ]	X=-5800.72
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #70	E=0	R$=[I ]	A$=[I ]	X=29686.4
	F=0	S$=[I ]
*** TEST PASSED ***
TESTCASE #71	E=0	R$=[    ss  ]	A$=[    ss  ]	X=2571
	F=0	S$=[    ss  ]
*** TEST PASSED ***
TESTCASE #72	E=0	R$=[  f ]	A$=[  f ]	X=31091
	F=0	S$=[  f ]
*** TEST PASSED ***
TESTCASE #73	E=0	R$=[   D  ]	A$=[   D  ]	X=14819
	F=0	S$=[   D  ]
*** TEST PASSED ***
TESTCASE #74	E=0	R$=[###    ]	A$=[###    ]	X=3790.9
	F=0	S$=[###    ]
*** TEST PASSED ***
TESTCASE #75	E=1	R$=[]	A$=[    '     ]	X=-4.2981e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #76	E=1	R$=[]	A$=[  dd    ]	X=-705453000
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #77	E=1	R$=[]	A$=[ TT    ]	X=-3.10179e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #78	E=1	R$=[]	A$=[  vvv ]	X=-4.86159e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #79	E=1	R$=[]	A$=[    X ]	X=-862908000
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #80	E=1	R$=[]	A$=[    %   ]	X=-3.4101e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #81	E=0	R$=[  ]	A$=[  ]	X=3.3889e+09
	F=0	S$=[  ]
*** TEST PASSED ***
TESTCASE #82	E=0	R$=[ 5555   ]	A$=[ 5555   ]	X=2.49826e+09
	F=0	S$=[ 5555   ]
*** TEST PASSED ***
TESTCASE #83	E=0	R$=[FFFF   ]	A$=[FFFF   ]	X=2.3491e+09
	F=0	S$=[FFFF   ]
*** TEST PASSED ***
TESTCASE #84	E=0	R$=[     %%  ]	A$=[     %%  ]	X=194745000
	F=0	S$=[     %%  ]
*** TEST PASSED ***
TESTCASE #85	E=0	R$=[     ]	A$=[     ]	X=2.02475e+09
	F=0	S$=[     ]
*** TEST PASSED ***
TESTCASE #86	E=1	R$=[]	A$=[  ~~~~    ]	X=-2.26748e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #87	E=1	R$=[]	A$=[   ||    ]	X=-2.10587e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #88	E=0	R$=[     SSS     ]	A$=[     SSS     ]	X=4.23585e+09
	F=0	S$=[     SSS     ]
*** TEST PASSED ***
TESTCASE #89	E=1	R$=[]	A$=[   6666 ]	X=-2.66524e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #90	E=0	R$=[    ww   ]	A$=[    ww   ]	X=4.01052e+09
	F=0	S$=[    ww   ]
*** TEST PASSED ***
TESTCASE #91	E=1	R$=[]	A$=[  1111   ]	X=-4.87912e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #92	E=0	R$=[ K ]	A$=[ K ]	X=1.77556e+09
	F=0	S$=[ K ]
*** TEST PASSED ***
TESTCASE #93	E=0	R$=[  ttttt ]	A$=[  ttttt ]	X=287705000
	F=0	S$=[  ttttt ]
*** TEST PASSED ***
TESTCASE #94	E=0	R$=[ OOOOO   ]	A$=[ OOOOO   ]	X=199977000
	F=0	S$=[ OOOOO   ]
*** TEST PASSED ***
TESTCASE #95	E=1	R$=[]	A$=[ E  ]	X=-3.39941e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #96	E=1	R$=[]	A$=[ PPPPP   ]	X=-3.49119e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #97	E=1	R$=[]	A$=[    == ]	X=-2.86324e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #98	E=0	R$=[ VVVV    ]	A$=[ VVVV    ]	X=4.20418e+09
	F=0	S$=[ VVVV    ]
*** TEST PASSED ***
TESTCASE #99	E=1	R$=[]	A$=[ c   ]	X=-3.1518e+09
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #100	E=0	R$=[    yyyy     ]	A$=[    yyyy     ]	X=4.60615e+09
	F=0	S$=[    yyyy     ]
*** TEST PASSED ***
*** ALL TESTS PASSED ***
