TESTCASE #1	E=1	R$=[]	X=0	A$=[]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #2	E=0	R$=[ ]	X=1	A$=[ ]
	F=0	S$=[ ]
*** TEST PASSED ***
TESTCASE #3	E=1	R$=[]	X=-1	A$=[3]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #4	E=0	R$=[]	X=0.4	A$=[z]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #5	E=0	R$=[]	X=-0.4	A$=[  ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #6	E=0	R$=[]	X=0.6	A$=[ 3]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #7	E=0	R$=[]	X=-0.6	A$=[ z]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #8	E=0	R$=[3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333]	X=100	A$=[3 ]
	F=0	S$=[3333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333333]
*** TEST PASSED ***
TESTCASE #9	E=0	R$=[zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz]	X=100	A$=[z ]
	F=0	S$=[zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz]
*** TEST PASSED ***
TESTCASE #12	E=0	R$=[]	X=-0.227229	A$=[ LLLL]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #13	E=0	R$=[]	X=-0.239157	A$=[    ''    ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #14	E=0	R$=[]	X=-0.213586	A$=[   oo     ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #15	E=0	R$=[]	X=0.274675	A$=[ 00  ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #16	E=0	R$=[]	X=0.169766	A$=[   \\\\  ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #17	E=0	R$=[]	X=0.318766	A$=[ lllll  ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #18	E=0	R$=[]	X=0.0206658	A$=[    uuuu  ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #19	E=0	R$=[]	X=0.188257	A$=[  a  ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #20	E=0	R$=[]	X=-0.277537	A$=[       ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #21	E=0	R$=[]	X=-0.481303	A$=[ hh     ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #22	E=0	R$=[]	X=0.43556	A$=[  h   ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #23	E=0	R$=[]	X=-0.210971	A$=[ )]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #24	E=0	R$=[]	X=-0.455216	A$=[    5   ]
	F=0	S$=[]
*** TEST PASSED ***
TESTCASE #25	E=1	R$=[]	X=-110.907	A$=[  2 ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #26	E=0	R$=[                                                                                                         ]	X=105.632	A$=[ -   ]
	F=0	S$=[                                                                                                         ]
*** TEST PASSED ***
TESTCASE #27	E=1	R$=[]	X=-114.341	A$=[dd ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #28	E=0	R$=[                                                                                                             ]	X=109.706	A$=[  tttt   ]
	F=0	S$=[                                                                                                             ]
*** TEST PASSED ***
TESTCASE #29	E=0	R$=[                                                                                                             ]	X=109.198	A$=[  ::::   ]
	F=0	S$=[                                                                                                             ]
*** TEST PASSED ***
TESTCASE #30	E=0	R$=[                                                                                     ]	X=85.8773	A$=[   ___   ]
	F=0	S$=[                                                                                     ]
*** TEST PASSED ***
TESTCASE #31	E=1	R$=[]	X=-58.3548	A$=[     ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #32	E=0	R$=[                             ]	X=29.6397	A$=[       ]
	F=0	S$=[                             ]
*** TEST PASSED ***
TESTCASE #33	E=1	R$=[]	X=-108.36	A$=[ _____  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #34	E=1	R$=[]	X=-46.5199	A$=[ S ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #35	E=0	R$=[                                                                                                                ]	X=112.521	A$=[  FFFF ]
	F=0	S$=[                                                                                                                ]
*** TEST PASSED ***
TESTCASE #36	E=0	R$=[                                             ]	X=45.4151	A$=[    kkk]
	F=0	S$=[                                             ]
*** TEST PASSED ***
TESTCASE #37	E=0	R$=[                                                                                                     ]	X=101.129	A$=[    NNNN  ]
	F=0	S$=[                                                                                                     ]
*** TEST PASSED ***
TESTCASE #38	E=0	R$=[                                                                 ]	X=65.0473	A$=[   mmmm  ]
	F=0	S$=[                                                                 ]
*** TEST PASSED ***
TESTCASE #39	E=0	R$=[                                                ]	X=48.4012	A$=[    ,,,,, ]
	F=0	S$=[                                                ]
*** TEST PASSED ***
TESTCASE #40	E=0	R$=[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO]	X=122.294	A$=[OO   ]
	F=0	S$=[OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO]
*** TEST PASSED ***
TESTCASE #41	E=1	R$=[]	X=-56.1094	A$=[   HHHH  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #42	E=1	R$=[]	X=-121.087	A$=[ < ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #43	E=1	R$=[]	X=-123.517	A$=[   j    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #44	E=1	R$=[]	X=-97.6301	A$=[    yyyy    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #45	E=1	R$=[]	X=-64.0001	A$=[  +++ ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #46	E=1	R$=[]	X=-25.6888	A$=[o  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #47	E=0	R$=[              ]	X=14.8006	A$=[    ((]
	F=0	S$=[              ]
*** TEST PASSED ***
TESTCASE #48	E=1	R$=[]	X=-61.0877	A$=[     uu     ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #49	E=1	R$=[]	X=-66.6381	A$=[    00     ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #50	E=1	R$=[]	X=-5476.5	A$=[     HH  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #51	E=1	R$=[]	X=-21210.3	A$=[     ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #52	E=1	R$=[]	X=-28757.2	A$=[  G   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #53	E=1	R$=[]	X=-28732.2	A$=[    {{{{ ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #55	E=1	R$=[]	X=-1830.69	A$=[CCC]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #59	E=1	R$=[]	X=-28930.6	A$=[     FFFF  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #60	E=1	R$=[]	X=-6014.53	A$=[ n   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #62	E=1	R$=[]	X=-10538.3	A$=[555    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #63	E=1	R$=[]	X=-17536.3	A$=[    YYYY ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #64	E=1	R$=[]	X=-8856.62	A$=[    w     ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #65	E=1	R$=[]	X=-5140.12	A$=[MMMM ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #66	E=1	R$=[]	X=-8595.31	A$=[ JJJJ    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #67	E=1	R$=[]	X=-3382.87	A$=[    %%    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #68	E=1	R$=[]	X=-5002.07	A$=[     *  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #69	E=1	R$=[]	X=-5800.72	A$=[    @@@   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #75	E=1	R$=[]	X=-4.2981e+09	A$=[    '     ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #76	E=1	R$=[]	X=-705453000	A$=[  dd    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #77	E=1	R$=[]	X=-3.10179e+09	A$=[ TT    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #78	E=1	R$=[]	X=-4.86159e+09	A$=[  vvv ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #79	E=1	R$=[]	X=-862908000	A$=[    X ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #80	E=1	R$=[]	X=-3.4101e+09	A$=[    %   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #81	E=1	R$=[]	X=3.3889e+09	A$=[  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #82	E=1	R$=[]	X=2.49826e+09	A$=[ 5555   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #83	E=1	R$=[]	X=2.3491e+09	A$=[FFFF   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #84	E=1	R$=[]	X=194745000	A$=[     %%  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #85	E=1	R$=[]	X=2.02475e+09	A$=[     ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #86	E=1	R$=[]	X=-2.26748e+09	A$=[  ~~~~    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #87	E=1	R$=[]	X=-2.10587e+09	A$=[   ||    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #88	E=1	R$=[]	X=4.23585e+09	A$=[     SSS     ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #89	E=1	R$=[]	X=-2.66524e+09	A$=[   6666 ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #90	E=1	R$=[]	X=4.01052e+09	A$=[    ww   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #91	E=1	R$=[]	X=-4.87912e+09	A$=[  1111   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #92	E=1	R$=[]	X=1.77556e+09	A$=[ K ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #93	E=1	R$=[]	X=287705000	A$=[  ttttt ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #94	E=1	R$=[]	X=199977000	A$=[ OOOOO   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #95	E=1	R$=[]	X=-3.39941e+09	A$=[ E  ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #96	E=1	R$=[]	X=-3.49119e+09	A$=[ PPPPP   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #97	E=1	R$=[]	X=-2.86324e+09	A$=[    == ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #98	E=1	R$=[]	X=4.20418e+09	A$=[ VVVV    ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #99	E=1	R$=[]	X=-3.1518e+09	A$=[ c   ]
	F=1	S$=[]
*** TEST PASSED ***
TESTCASE #100	E=1	R$=[]	X=4.60615e+09	A$=[    yyyy     ]
	F=1	S$=[]
*** TEST PASSED ***
*** ALL TESTS PASSED ***
