   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *

   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *


ENTER  (H) for  HOME  Location ...
       (W) for Wilmington / Wrightsville Beach area
       (M) for Myrtle Beach area
       (C) for Charleston area.

or just press <cr> to input your own Local Coordinates: H

   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *

What is the Name of the Hurricane TOMCAT

Input LATITUDE of Hurricane TOMCAT in Degrees34.56

Input LONGITUDE of Hurricane TOMCAT in Degrees78.91

What is TOMCAT's Current Direction of Travel (in Degrees)123

What is TOMCAT's Current Speed (MPH)45

   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *

***************************************************************
HURRICANE TOMCAT is Currently 116 Miles SOUTHEAST Of
East Charlotte.   Bearing From East Charlotte
IS 112  Degrees From True North.
***************************************************************
If Hurricane TOMCAT Maintains its Current Speed of 45(mph)
THERE IS NO CAUSE FOR ALARM. Please Continue To Monitor
Hurricane TOMCAT Closely.
***************************************************************


  N O A A Weather Radio

 Charlotte          162.475  MHz
 Wilmington NC      162.55
 Myrtle Beach SC    162.4
 Charleston   SC    162.55
 Beaufort     SC    162.475
 Cape Hatteras      162.55


Press <cr> to Input New Status On Hurricane TOMCAT

   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *

Input LATITUDE of Hurricane TOMCAT in Degrees34.56

Input LONGITUDE of Hurricane TOMCAT in Degrees78.91

What is TOMCAT's Current Direction of Travel (in Degrees)-135

What is TOMCAT's Current Speed (MPH)67

   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *

   * * * H U R R I C A N E * * * 
   * * *    A L E R T    * * *
   * * * H U R R I C A N E * * * 
   * * *    A L E R T    * * *
   * * * H U R R I C A N E * * * 
   * * *    A L E R T    * * *
   * * * H U R R I C A N E * * * 
   * * *    A L E R T    * * *
   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *

   * * *   H U R C O N  1  N O W   I N   E F F E C T  * * *
***************************************************************
HURRICANE TOMCAT IS CURRENTLY 116MILES SOUTHEAST OF East Charlotte
BEARING FROM East Charlotte: 112 DEGREES FROM TRUE NORTH.
***************************************************************
IF THIS HURRICANE MAINTAINS ITS CURRENT SPEED OF 67 MILES
PER HOUR AND CURRENT DIRECTION OF -135 DEGREES, THE CENTER
OF THE STORM CAN BE EXPECTED TO HIT THE East Charlotte
AREA IN APPROXIMATELY 1 HOURS.
***************************************************************
PRESS LETTER  - H - TO INPUT NEW STATUS ON HURRICANE
      PRESS LETTER  - C - TO REVIEW HURRICANE CONDITION NUMBERS    * * *   H U R R I C A N E   W A R N I N G   * * *
                                                        
C

          H U R R I C A N E   C O N D I T I O N S 

       A. H U R C O N   5 :  A HURRICANE READINESS STATUS
       CONSISTANT WITH SOUND PRECAUTIONARY MEASURES EFFECTIVE
       JUNE 1 THROUGH NOVEMBER 30 EACH YEAR.

       B. H U R C O N   4:  A HURRICANE HAS BECOME A THREAT
       TO THE East Charlotte AREA. SURFACE WINDS IN EXCESS OF 50
       COULD ARRIVE WITHIN 72 HOURS.

       C. H U R C O N   3:  A HURRICANE HAS BECOME A THREAT
       TO THE East Charlotte AREA.  SURFACE WINDS IN EXCESS OF 50
       KNOTS COULD ARRIVE WITHIN 48 HOURS.

     Press  <<cr>> To Continue

       H U R R I C A N E   C O N D I T I O N S

       D. H U R C O N   2:  A HURRICANE HAS BECOME A THREAT
       TO THE East Charlotte AREA.  SURFACE WINDS IN EXCESS OF 50
       KNOTS COULD ARRIVE WITHIN 24 HOURS.

       E. H U R C O N   1:  A HURRICANE HAS BECOME A THREAT
       TO THE East Charlotte AREA.  SURFACE WINDS IN EXCESS OF 50
       KNOTS COULD ARRIVE WITHIN 12 HOURS.


    Press <<cr>> To Continue
   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *

   * * *   H U R C O N  1  N O W   I N   E F F E C T  * * *
***************************************************************
HURRICANE TOMCAT IS CURRENTLY 116MILES SOUTHEAST OF East Charlotte
BEARING FROM East Charlotte: 112 DEGREES FROM TRUE NORTH.
***************************************************************
IF THIS HURRICANE MAINTAINS ITS CURRENT SPEED OF 67 MILES
PER HOUR AND CURRENT DIRECTION OF -135 DEGREES, THE CENTER
OF THE STORM CAN BE EXPECTED TO HIT THE East Charlotte
AREA IN APPROXIMATELY 1 HOURS.
***************************************************************
PRESS LETTER  - H - TO INPUT NEW STATUS ON HURRICANE
      PRESS LETTER  - C - TO REVIEW HURRICANE CONDITION NUMBERS    * * *   H U R R I C A N E   W A R N I N G   * * *
                                                        
H

   * * *  HURRICANE LOCATION AND DISTANCE CALCULATOR  * * *

Input LATITUDE of Hurricane TOMCAT in Degrees0

Input LONGITUDE of Hurricane TOMCAT in Degrees0
